### ISSUE TITLE
Need to add CA certificates to the Docker image in order to communicate with the API though https

### ISSUE THREAD

**Issue by icot** [cerndb/dbod-web#59]
```
Error: unable to verify the first certificate
 at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
 at emitNone (events.js:105:13)
 at TLSSocket.emit (events.js:207:7)
 at TLSSocket._finishInit (_tls_wrap.js:628:8)
 at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)
```

**Comment by icot** [comment]
Fixed
